[theme]
primaryColor = "#2ecc71"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
port = 8501
